[package]
name = "rust-top-audit"
version = "0.1.0"
authors = ["GitHub Actions on behalf of Jens Brimfors <jens.brimfors@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = "1.0.39"
rand = "0.7.3"
quote = "1.0.7"
proc-macro2 = "1.0.19"
unicode-xid = "0.2.1"
rand_core = "0.5.1"
autocfg = "1.0.1"
libc = "0.2.76"
base64 = "0.12.3"
serde = "1.0.115"
log = "0.4.11"
num-traits = "0.2.12"
smallvec = "1.4.2"
rand_chacha = "0.2.2"
serde_derive = "1.0.115"
lazy_static = "1.4.0"
serde_json = "1.0.57"
cfg-if = "0.1.10"
cc = "1.0.59"
version_check = "0.9.2"
bitflags = "1.2.1"
time = "0.2.16"
byteorder = "1.3.4"
regex-syntax = "0.6.18"
regex = "1.3.9"
itoa = "0.4.6"
ryu = "1.0.5"
percent-encoding = "2.1.0"
memchr = "2.3.3"
aho-corasick = "0.7.13"
bytes = "0.5.6"
url = "2.1.1"
num-integer = "0.1.43"
crossbeam-utils = "0.7.2"
idna = "0.2.0"
parking_lot_core = "0.8.0"
num_cpus = "1.13.0"
parking_lot = "0.11.0"
indexmap = "1.5.1"
scopeguard = "1.1.0"
futures = "0.3.5"
thread_local = "1.0.1"
fnv = "1.0.7"
ppv-lite86 = "0.2.9"
chrono = "0.4.15"
unicode-width = "0.1.8"
atty = "0.2.14"
tokio = "0.2.22"
winapi = "0.3.9"
either = "1.6.0"
generic-array = "0.14.4"
unicode-normalization = "0.1.13"
strsim = "0.10.0"
semver = "0.10.0"
getrandom = "0.1.14"
slab = "0.4.2"
clap = "2.33.3"
lock_api = "0.4.1"
backtrace = "0.3.50"
miniz_oxide = "0.4.1"
mio = "0.7.0"
pkg-config = "0.3.18"
proc-macro-hack = "0.5.18"
semver-parser = "0.9.0"
http = "0.2.1"
itertools = "0.9.0"
once_cell = "1.4.1"
hyper = "0.13.7"
net2 = "0.2.34"
ansi_term = "0.12.1"
matches = "0.1.8"
crossbeam-queue = "0.2.3"
unicode-bidi = "0.3.4"
vec_map = "0.8.2"
memoffset = "0.5.5"
iovec = "0.1.4"
digest = "0.9.0"
rustc-demangle = "0.1.16"
rand_hc = "0.2.0"
textwrap = "0.12.1"
typenum = "1.12.0"
h2 = "0.2.6"
block-buffer = "0.9.0"
crossbeam-epoch = "0.8.2"
env_logger = "0.7.1"
pin-project = "0.4.23"
pin-project-internal = "0.4.23"
rustc_version = "0.2.3"
unicase = "2.6.0"
futures-core = "0.3.5"
crossbeam-deque = "0.7.3"
rand_pcg = "0.2.1"
futures-util = "0.3.5"
futures-task = "0.3.5"
maybe-uninit = "2.0.0"
opaque-debug = "0.3.0"
pin-utils = "0.1.0"
futures-channel = "0.3.5"
futures-sink = "0.3.5"
synstructure = "0.12.4"
quick-error = "2.0.0"
want = "0.3.0"
dtoa = "0.4.6"
futures-io = "0.3.5"
mime = "0.3.16"
pin-project-lite = "0.1.7"
toml = "0.5.6"
arrayvec = "0.5.1"
http-body = "0.3.1"
tokio-util = "0.3.1"
remove_dir_all = "0.6.0"
httparse = "1.3.4"
termcolor = "1.1.0"
proc-macro-nested = "0.1.6"
humantime = "2.0.1"
futures-macro = "0.3.5"
socket2 = "0.3.12"
byte-tools = "0.3.1"
same-file = "1.0.6"
linked-hash-map = "0.5.3"
walkdir = "2.3.1"
futures-executor = "0.3.5"
crc32fast = "1.2.0"
dirs = "3.0.1"
openssl-sys = "0.9.58"
unicode-segmentation = "1.6.0"
serde_urlencoded = "0.6.1"
failure = "0.1.8"
flate2 = "1.0.17"
uuid = "0.8.1"
hex = "0.4.2"
try-lock = "0.2.3"
gimli = "0.22.0"
block-padding = "0.2.1"
object = "0.21.1"
mime_guess = "2.0.3"
thiserror = "1.0.20"
thiserror-impl = "1.0.20"
fake-simd = "0.1.2"
addr2line = "0.13.0"
glob = "0.3.0"
heck = "0.3.1"
failure_derive = "0.1.8"
nom = "5.1.2"
rand_xorshift = "0.2.0"
adler32 = "1.2.0"
arc-swap = "0.4.7"
tempfile = "3.1.0"
openssl = "0.10.30"
encoding_rs = "0.8.24"
hashbrown = "0.8.2"
rayon = "1.4.0"
rayon-core = "1.8.0"
mio-uds = "0.6.8"
crossbeam-channel = "0.4.3"
sha2 = "0.9.1"
foreign-types = "0.5.0"
foreign-types-shared = "0.3.0"
openssl-probe = "0.1.2"
tower-service = "0.3.0"
anyhow = "1.0.32"
error-chain = "0.12.4"
subtle = "2.2.3"
proc-macro-error = "1.0.4"
bstr = "0.2.13"
reqwest = "0.10.8"
nix = "0.18.0"
native-tls = "0.2.4"
void = "1.0.2"
dirs-sys = "0.3.5"
proc-macro-error-attr = "1.0.4"
rand_os = "0.2.2"
hyper-tls = "0.4.3"
rand_isaac = "0.2.0"
miow = "0.3.5"
num-bigint = "0.3.0"
tinyvec = "1.0.0"
tokio-macros = "0.2.5"
spin = "0.5.2"
structopt-derive = "0.4.10"
yaml-rust = "0.4.4"
structopt = "0.3.17"
rand_jitter = "0.2.0"
winapi-x86_64-pc-windows-gnu = "0.4.0"
signal-hook-registry = "1.2.1"
sha-1 = "0.9.1"
regex-automata = "0.1.9"
winapi-i686-pc-windows-gnu = "0.4.0"
async-trait = "0.1.40"
tracing = "0.1.19"
hermit-abi = "0.1.15"
scoped-tls = "1.0.0"
tracing-core = "0.1.15"
winapi-util = "0.1.5"
siphasher = "0.3.3"
adler = "0.2.3"
crypto-mac = "0.9.1"
ring = "0.16.15"
redox_syscall = "0.2.1"
num-rational = "0.3.0"
which = "4.0.2"
untrusted = "0.7.1"
wasi = "0.10.0"
filetime = "0.2.12"
tokio-tls = "0.3.1"
wasm-bindgen = "0.2.67"
phf_shared = "0.8.0"
static_assertions = "1.1.0"
wasm-bindgen-macro = "0.2.67"
wasm-bindgen-backend = "0.2.67"
wasm-bindgen-macro-support = "0.2.67"
tokio-executor = "0.1.10"
bumpalo = "3.4.0"
tokio-timer = "0.2.13"
wasm-bindgen-shared = "0.2.67"
syn-mid = "0.5.0"
tokio-io = "0.1.13"
lazycell = "1.3.0"
stable_deref_trait = "1.2.0"
tokio-sync = "0.1.8"
hmac = "0.9.0"
js-sys = "0.3.44"
derive_more = "0.99.9"
num-iter = "0.1.41"
tokio-reactor = "0.1.12"
kernel32-sys = "0.2.2"
winapi-build = "0.1.1"
backtrace-sys = "0.1.37"
csv = "1.1.3"
phf = "0.8.0"
web-sys = "0.3.44"
petgraph = "0.5.1"
maplit = "1.0.2"
csv-core = "0.1.10"
tokio-tcp = "0.1.4"
cloudabi = "0.1.0"
fixedbitset = "0.3.1"
libz-sys = "1.1.0"
tokio-threadpool = "0.1.18"
term = "0.6.1"
phf_generator = "0.8.0"
tokio-current-thread = "0.1.7"
nodrop = "0.1.14"
jobserver = "0.1.21"
libloading = "0.6.3"
rustls = "0.18.1"
num-complex = "0.3.0"
core-foundation-sys = "0.8.0"
ws2_32-sys = "0.2.1"
core-foundation = "0.9.0"
serde_yaml = "0.8.13"
ahash = "0.4.4"
tracing-attributes = "0.1.11"
zeroize = "1.1.0"
safemem = "0.3.3"
vcpkg = "0.2.10"
webpki = "0.21.3"
constant_time_eq = "0.1.5"
schannel = "0.1.19"
difference = "2.0.0"
sct = "0.6.0"
lru-cache = "0.1.2"
shlex = "0.1.1"
arrayref = "0.3.6"
phf_codegen = "0.8.0"
fuchsia-zircon-sys = "0.3.3"
fuchsia-zircon = "0.3.3"
rustc-hash = "1.1.0"
bit-vec = "0.6.2"
bincode = "1.3.1"
cookie = "0.14.2"
instant = "0.1.6"
pest = "2.1.3"
num = "0.3.0"
security-framework = "2.0.0"
tokio-uds = "0.2.7"
webpki-roots = "0.20.0"
hostname = "0.3.1"
tokio-codec = "0.1.2"
tokio-rustls = "0.14.0"
futures-cpupool = "0.1.8"
ucd-trie = "0.1.3"
sha1 = "0.6.0"
wasm-bindgen-futures = "0.4.17"
criterion = "0.3.3"
string = "0.2.1"
pest_generator = "2.1.3"
lexical-core = "0.7.4"
memmap = "0.7.0"
criterion-plot = "0.4.3"
security-framework-sys = "2.0.0"
winreg = "0.7.0"
language-tags = "0.2.2"
pest_meta = "2.1.3"
colored = "2.0.0"
pest_derive = "2.1.0"
tokio-udp = "0.1.6"
tokio-fs = "0.1.7"
bindgen = "0.55.1"
xml-rs = "0.8.3"
threadpool = "1.8.1"
ordered-float = "2.0.0"
md5 = "0.7.0"
cast = "0.2.3"
fuchsia-cprng = "0.1.1"
tinytemplate = "1.1.0"
rdrand = "0.7.0"
fxhash = "0.2.1"
tokio-buf = "0.1.1"
owning_ref = "0.4.1"
crossbeam = "0.7.3"
clang-sys = "1.0.0"
doc-comment = "0.3.3"
oorandom = "11.1.2"
tar = "0.4.29"
cexpr = "0.4.0"
plotters = "0.2.15"
globset = "0.4.5"
libgit2-sys = "0.12.12"
utf-8 = "0.7.5"
console = "0.12.0"
strum_macros = "0.19.2"
git2 = "0.13.10"
getopts = "0.2.21"
blake2b_simd = "0.5.10"
cargo_metadata = "0.11.1"
strum = "0.19.2"
peeking_take_while = "0.1.2"
mio-extras = "2.0.6"
trust-dns-proto = "0.19.5"
redox_users = "0.3.5"
cmake = "0.1.44"
futures-timer = "3.0.2"
derivative = "2.1.1"
const-random = "0.1.8"
const-random-macro = "0.1.8"
multimap = "0.8.2"
utf8-ranges = "1.0.4"
pretty_assertions = "0.6.1"
ctor = "0.1.15"
match_cfg = "0.1.0"
approx = "0.3.2"
time-macros-impl = "0.1.1"
time-macros = "0.1.0"
trust-dns-resolver = "0.19.5"
async-task = "3.0.0"
prost-derive = "0.6.1"
prost = "0.6.1"
standback = "0.2.10"
proc-macro-crate = "0.1.5"
data-encoding = "2.3.0"
tracing-subscriber = "0.2.11"
rust-argon2 = "0.8.2"
hyper-rustls = "0.21.0"
rustc-serialize = "0.3.24"
mio-named-pipes = "0.1.7"
enum-as-inner = "0.3.3"
c2-chacha = "0.2.4"
tracing-futures = "0.2.4"
prost-types = "0.6.1"
pulldown-cmark = "0.7.2"
aes-soft = "0.5.0"
prost-build = "0.6.1"
signal-hook = "0.1.16"
termios = "0.3.2"
resolv-conf = "0.6.3"
xattr = "0.2.2"
tempdir = "0.3.7"
bit-set = "0.5.2"
async-std = "1.6.3"
gcc = "0.3.55"
half = "1.6.0"
paste = "1.0.0"
deflate = "0.8.6"
kv-log-macro = "1.0.7"
synom = "0.11.3"
traitobject = "0.1.0"
publicsuffix = "1.5.4"
darling = "0.10.2"
darling_core = "0.10.2"
darling_macro = "0.10.2"
matchers = "0.0.1"
wait-timeout = "0.2.0"
protobuf = "2.17.0"
paste-impl = "0.1.18"
png = "0.16.7"
curl-sys = "0.4.36"
handlebars = "3.4.0"
utf8parse = "0.2.0"
fallible-iterator = "0.2.0"
ident_case = "1.0.1"
take_mut = "0.2.2"
copyless = "0.1.5"
try_from = "0.3.2"
sized-chunks = "0.6.2"
aes = "0.5.0"
serde_cbor = "0.11.1"
tracing-log = "0.1.1"
notify = "4.0.15"
dotenv = "0.15.0"
curl = "0.4.33"
unreachable = "1.0.0"
ipnet = "2.3.0"
urlencoding = "1.1.1"
sharded-slab = "0.0.9"
image = "0.23.8"
rustversion = "1.0.3"
crc = "1.8.1"
libssh2-sys = "0.2.19"
num-derive = "0.3.2"
string_cache = "0.8.0"
inotify = "0.8.3"
ascii = "1.0.0"
build_const = "0.2.1"
new_debug_unreachable = "1.0.4"
cookie_store = "0.12.0"
precomputed-hash = "0.1.1"
pem = "0.8.1"
zip = "0.5.6"
tower-layer = "0.3.0"
pretty_env_logger = "0.4.0"
quickcheck = "0.9.2"
tungstenite = "0.11.1"
home = "0.5.3"
input_buffer = "0.3.1"
parking = "2.0.0"
podio = "0.2.0"
ignore = "0.4.16"
terminal_size = "0.1.13"
encode_unicode = "0.3.6"
cpuid-bool = "0.1.2"
inotify-sys = "0.1.3"
headers = "0.3.2"
headers-core = "0.2.0"
crunchy = "0.2.2"
rand_xoshiro = "0.4.0"
actix-threadpool = "0.3.3"
curve25519-dalek = "3.0.0"
block-cipher-trait = "0.7.0"
scoped_threadpool = "0.1.9"
actix-rt = "1.1.1"
twoway = "0.2.1"
smol = "0.4.2"
fs_extra = "1.2.0"
tiny-keccak = "2.0.2"
prometheus = "0.9.0"
combine = "4.3.1"
string_cache_codegen = "0.5.1"
rusttype = "0.9.2"
ucd-util = "0.1.8"
md-5 = "0.9.1"
tracing-serde = "0.1.1"
zeroize_derive = "1.0.0"
aead = "0.3.2"
directories = "3.0.1"
universal-hash = "0.4.0"
libflate = "1.0.2"
async-stream = "0.3.0"
async-stream-impl = "0.3.0"
ct-logs = "0.7.0"
tower-util = "0.3.1"
blocking = "0.6.1"
rustls-native-certs = "0.4.0"
openssl-src = "111.10.2"
actix-connect = "1.0.2"
actix-service = "1.0.6"
sha3 = "0.9.1"
jpeg-decoder = "0.1.20"
actix-utils = "2.0.0"
libsqlite3-sys = "0.20.0"
fastrand = "1.3.4"
actix-http = "1.0.1"
actix-codec = "0.3.0"
bytemuck = "1.4.0"
concurrent-queue = "1.2.2"
quick-xml = "0.18.1"
keccak = "0.1.0"
tower-limit = "0.3.1"
cache-padded = "1.1.1"
brotli-sys = "0.3.2"
brotli2 = "0.3.2"
actix-web = "2.0.0"
slog = "2.5.2"
polyval = "0.4.0"
tower = "0.3.1"
tower-discover = "0.3.0"
tower-timeout = "0.3.0"
tower-buffer = "0.3.0"
tower-retry = "0.3.0"
tower-load-shed = "0.3.0"
aes-gcm = "0.6.0"
ghash = "0.3.0"
tokio-signal = "0.2.9"
lru = "0.6.0"
warp = "0.2.4"
serde_repr = "0.1.6"
waker-fn = "1.1.0"
actix-macros = "0.1.2"
buf_redux = "0.8.4"
