name: Rust top dependency audit
on:
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC
  push:
    paths:
      - '**/Cargo.toml'
      - 'Cargo.lock'
      - '.github/workflows/*.yml'
  pull_request:
    branches: [ master ]
jobs:
  check-dependency-versions:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install cargo-edit
        run: cargo install cargo-edit
      - name: Add dependencies
        run: |
          for crate in $(curl "https://crates.io/api/v1/crates?page=1&per_page=50&sort=recent-downloads" | jq -r ".crates[] | .id"   )
          do
            cargo add "$crate"
          done
      - uses: actions-rs/audit-check@v1.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
