name: Rust top dependency audit

on:
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC
  push:
    paths:
      - '**/Cargo.toml'
      - 'Cargo.lock'
      - '.github/workflows/*.yml'
  pull_request:
    branches: [ master ]

jobs:
  check-dependency-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Cache cargo bin
        uses: actions/cache@v1
        with:
          path: ~/.cargo/bin
          key: ${{ runner.os }}-cargo-bin-${{ hashFiles('~/.cargo/bin/*') }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install cargo-edit
        run: cargo install cargo-edit --version 0.6.0
      - name: Add dependencies
        run: ./add_top_crates.sh
#      - name: Cargo audit - for GH-issues
#        uses: actions-rs/audit-check@v1.2.0
#        with:
#          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install cargo-audit
        run: cargo install cargo-audit --version 0.12.0
      - name: Cargo audit
        run: cargo audit -D
