name: Rust top dependency audit

on:
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ master ]

jobs:
  check-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Cache cargo bin
        uses: actions/cache@v1
        with:
          path: ~/.cargo/bin
          key: ${{ runner.os }}-cargo-bin-${{ hashFiles('~/.cargo/bin/*') }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Perform audit
        run: bash perform_audit.sh GO
